services:
  app:
    image: node:23-alpine3.20
    working_dir: /frieren-stats-site
    volumes:
      - .:/frieren-stats-site
      - /frieren-stats-site/node_modules # Prevents node_modules from being overwritten by the container during development
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydatabase
      WATCHPACK_POLLING: true
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: