services:
  app:
    image: node:18-alpine
    working_dir: /frieren-stats-site
    volumes:
      - .:/frieren-stats-site
    build: .
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydatabase
      WATCHPACK_POLLING: true
    ports:
      - "3000:3000"
      - "5555:5555"
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: